.PHONY: help setup deps deps-platform fmt lint test smoke \
        neon-create neon-load neon-read neon-summary neon-drop \
        dataset-export train stamp-revision db-migrate \
        collect check-residual collect-costs \
        docker-build docker-build-serving wheel dbx-upload sf-package \
        phase-train phase-register phase-deploy phase-predict phase-teardown phase-all \
        tf-init tf-plan tf-apply tf-destroy \
        clean

# Make はロジックを持たず CLI に委譲する。
# 秘密情報は Doppler 経由でのみ渡す（doppler run -- ...）。
# 対象基盤は ENV で切り替える: gcp-dev / aws-dev / azure-dev / dbx-dev / sf-dev / neon-dev

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

PYTHON  := .venv/bin/python
PYTEST  := .venv/bin/pytest
export PYTHONPATH := src

ENV       ?= gcp-dev
TF_DIR    := infra/environments/$(ENV)
DATASET     ?= data/california_housing.parquet
COLLECT_DIR ?= artifacts/fallback
ARTIFACTS ?= artifacts/local
DIST      ?= artifacts/dist

# フェーズ実行の対象基盤（vertex / sagemaker / azureml / databricks / snowflake）。
# ENV（terraform 環境）とは別物なので混同しない。
PLATFORM ?= vertex
PARAMS   ?= {}

## ヘルプを表示
help:
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	  | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

# --- セットアップ ---------------------------------------------------------

setup: deps ## 初期セットアップ（venv + 依存）
	@echo "Setup complete."

deps: ## 依存をインストール（pyproject.toml が正本）
	uv venv --python 3.12
	uv pip install -e ".[$(BASE_EXTRAS)]" --group dev

# 基盤 SDK は **基盤ごとに別 extra**（学習コンテナを太らせないため全部は入れない）。
# PLATFORM → pyproject の optional-dependencies キー。
BASE_EXTRAS      := neon,serving,config
EXTRA_vertex     := gcp
EXTRA_sagemaker  := aws
EXTRA_azureml    := azure
EXTRA_databricks := databricks
EXTRA_snowflake  := snowflake

deps-platform: ## 対象基盤の SDK を入れる（PLATFORM=vertex → gcp extra）。Phase 着手前に必須
	@test -n "$(EXTRA_$(PLATFORM))" || { echo "PLATFORM が不正: $(PLATFORM)"; exit 2; }
	uv pip install -e ".[$(BASE_EXTRAS),$(EXTRA_$(PLATFORM))]" --group dev

# --- 品質ゲート -----------------------------------------------------------

# scripts/ も対象に含める。実行系の本体（run_phase / run_terraform / distribute /
# check_residual）はここに居るので、外すと「動くコードの一部だけ無検査」になる。
LINT_PATHS := src tests scripts

fmt: ## フォーマット
	.venv/bin/ruff format $(LINT_PATHS)

lint: ## 静的解析
	.venv/bin/ruff check $(LINT_PATHS)

test: ## テスト
	$(PYTEST) tests/ -v

smoke: ## 最小疎通（残留検査を read-only で回す）
	doppler run -- $(PYTHON) scripts/check_residual.py --all --json

# --- Neon（計測到達点・学習データ）---------------------------------------

neon-create: ## california_housing テーブル作成
	doppler run -- $(PYTHON) -m platforms.neon.load create

neon-load: ## California Housing を Neon へロード（冪等）
	doppler run -- $(PYTHON) -m platforms.neon.load load

neon-read: ## 先頭数件を読み出し
	doppler run -- $(PYTHON) -m platforms.neon.load read --limit 5

neon-summary: ## 行数と目的変数の要約
	doppler run -- $(PYTHON) -m platforms.neon.load summary

neon-drop: ## テーブル削除
	doppler run -- $(PYTHON) -m platforms.neon.load drop

stamp-revision: ## code_revision をパッケージに焼き込む（wheel / stage 配布の直前に必ず実行）
	@sha=$$(git rev-parse HEAD) && \
	  printf '# generated by `make stamp-revision` — commit しない\nCODE_REVISION = "%s"\n' $$sha \
	  > src/core/ml/config/_stamp.py && echo "stamped: $$sha"

db-migrate: ## sql/schema.sql を Neon（direct endpoint）へ適用
	doppler run -- sh -c 'psql "$$NEON_MULTICLOUD_DIRECT_URI" -v ON_ERROR_STOP=1 -f sql/schema.sql'

# --- 学習（Phase 0: ローカル基準値）--------------------------------------

dataset-export: ## Neon -> 配布用 Parquet + checksum（5基盤への配布の起点）
	doppler run -- $(PYTHON) -m platforms.neon.load export --output $(DATASET)

train: ## ローカル学習（Phase 0 基準値の再現。BASELINE=1 で RF 健全性チェックも）
	$(PYTHON) -m core.ml.cli --input $(DATASET) --output $(ARTIFACTS) \
		$(if $(BASELINE),--with-baseline,)

collect: ## fallback JSONL を Neon へ流し込む（COLLECT_DIR 配下を回収）
	doppler run -- $(PYTHON) scripts/collect_jsonl.py --from-dir $(COLLECT_DIR)

check-residual: ## destroy 後の残留リソースを検査
	doppler run -- $(PYTHON) scripts/check_residual.py --all

# --- コンテナ（Tier A）----------------------------------------------------

IMAGE  ?= mcml-training
SERVING_IMAGE ?= mcml-serving
TAG    ?= latest

docker-build: ## 学習イメージをビルド（Tier A 3基盤共通）
	docker build -f docker/training/Dockerfile \
		--build-arg CODE_REVISION="$$(git rev-parse HEAD)" \
		-t $(IMAGE):$(TAG) .

docker-build-orchestrator: ## Vertex パイプラインの器（run_phase を動かすイメージ）をビルド
	docker build -f docker/orchestrator/Dockerfile \
		--build-arg CODE_REVISION="$$(git rev-parse HEAD)" \
		-t mcml-orchestrator:$(TAG) .

docker-build-serving: ## 推論イメージをビルド（Tier A 3契約を1イメージで満たす）
	docker build -f docker/serving/Dockerfile \
		--build-arg CODE_REVISION="$$(git rev-parse HEAD)" \
		-t $(SERVING_IMAGE):$(TAG) .

docker-push: ## Tier A のイメージを各基盤のレジストリへ push（PLATFORM=vertex|sagemaker|azureml）
	@test -n "$(PLATFORM)" || { echo "PLATFORM= を指定する（vertex|sagemaker|azureml）"; exit 2; }
	scripts/push_images.sh "$(PLATFORM)" "$(TAG)"

distribute: ## 学習データを各基盤のストレージへ配る（Tier B は adapter が運ぶ）
	doppler run -- $(PYTHON) scripts/distribute.py $(if $(PLATFORM),$(PLATFORM),--all)

# --- パッケージ（Tier B の統一単位）---------------------------------------
# wheel / zip の中に .git も CODE_REVISION も無いので、**必ず stamp してから**作る。

wheel: stamp-revision ## Databricks 配布用 wheel をビルド
	$(PYTHON) -m build --wheel --outdir $(DIST)

dbx-upload: wheel ## wheel と学習データを UC Volume へ置く（Databricks の②の前提）
	doppler run -- $(PYTHON) -c "from pathlib import Path; \
	from platforms.config import load_settings; \
	from platforms.databricks.adapter import DatabricksAdapter; \
	a = DatabricksAdapter(load_settings().databricks(), sink=None); \
	print(a.upload_wheel(Path('$(DIST)/multicloud_ml_platform_lab-0.1.0-py3-none-any.whl'))); \
	print(a.upload_dataset(Path('$(DATASET)')))"

sf-package: stamp-revision ## Snowflake stage 配布用 zip をビルド
	$(PYTHON) -c "from pathlib import Path; \
	from platforms.snowflake.adapter import SnowflakeAdapter, SnowflakeConfig; \
	print(SnowflakeAdapter(SnowflakeConfig(database='_', schema='_', warehouse='_'), sink=None) \
	  .build_package(Path('.'), Path('$(DIST)')))"

collect-costs: ## cost_snapshots を後追いで埋める（請求反映は1〜2日遅れる）
	doppler run -- $(PYTHON) scripts/collect_costs.py --all --days 7 --record

pipeline-build: ## マネージドパイプラインの定義を組む（PLATFORM=sagemaker|azureml・課金ゼロ）
	@test -n "$(PLATFORM)" || { echo "PLATFORM= を指定する（sagemaker|azureml）"; exit 2; }
	doppler run -- $(PYTHON) scripts/run_pipeline.py $(PLATFORM) build

pipeline-submit: ## ⚠️課金あり: パイプラインを投入（PLATFORM=sagemaker|azureml）
	@test -n "$(PLATFORM)" || { echo "PLATFORM= を指定する（sagemaker|azureml）"; exit 2; }
	doppler run -- $(PYTHON) scripts/run_pipeline.py $(PLATFORM) submit

# --- フェーズ実行（Golden Path ステップ2〜3）------------------------------
# PLATFORM=vertex|sagemaker|azureml|databricks|snowflake

phase-train: ## 学習ジョブ投入（失敗も ml_runs に記録）
	doppler run -- $(PYTHON) scripts/run_phase.py $(PLATFORM) train --params '$(PARAMS)'

phase-register: ## モデル登録
	doppler run -- $(PYTHON) scripts/run_phase.py $(PLATFORM) register

phase-deploy: ## エンドポイントへデプロイ（⚠️ 常時課金）
	doppler run -- $(PYTHON) scripts/run_phase.py $(PLATFORM) deploy

phase-predict: ## 1件オンライン推論（完了条件⑤）
	doppler run -- $(PYTHON) scripts/run_phase.py $(PLATFORM) predict

phase-teardown: ## デプロイしたものを落とす（残留検査の前に必ず）
	doppler run -- $(PYTHON) scripts/run_phase.py $(PLATFORM) teardown

phase-all: ## train -> register -> deploy -> predict を通しで
	doppler run -- $(PYTHON) scripts/run_phase.py $(PLATFORM) all --params '$(PARAMS)'

# --- Terraform ------------------------------------------------------------
# フェーズ末に必ず tf-destroy する（Tier A のエンドポイントは常時課金）。
# apply / destroy は run_terraform.py 経由で所要とリソース数を infra_events に残す
# （素の terraform だと Golden Path ステップ1の計測が空になる）。

tf-init: ## terraform init（ENV=gcp-dev 等）
	terraform -chdir=$(TF_DIR) init

tf-plan: ## terraform plan
	terraform -chdir=$(TF_DIR) plan

tf-apply: ## terraform apply（infra_event 記録つき）
	doppler run -- $(PYTHON) scripts/run_terraform.py apply --env $(ENV)

tf-destroy: ## terraform destroy -> 残留検査（infra_event 記録つき）
	doppler run -- $(PYTHON) scripts/run_terraform.py destroy --env $(ENV)
	$(MAKE) check-residual

# --- その他 ---------------------------------------------------------------

clean: ## 生成物を削除
	find src scripts tests -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true
